export const rawAnimals = [
    // Mammals
    "Lion",
    "Tiger",
    "Elephant",
    "Giraffe",
    "Zebra",
    "Monkey",
    "Gorilla",
    "Chimpanzee",
    "Lemur",
    "Kangaroo",
    "Koala",
    "Platypus",
    "Wombat",
    "Polar Bear",
    "Grizzly Bear",
    "Panda",
    "Red Panda",
    "Sloth",
    "Armadillo",
    "Anteater",
    "Tapir",
    "Capybara",
    "Meerkat",
    "Otter",
    "Beaver",
    "Porcupine",
    "Skunk",
    "Raccoon",
    "Badger",
    "Fox",
    "Wolf",
    "Coyote",
    "Hyena",
    "Jackal",
    "Dingo",
    "Jaguar",
    "Leopard",
    "Cheetah",
    "Cougar",
    "Bobcat",
    "Lynx",
    "Ocelot",
    "Serval",
    "Caracal",
    "Moose",
    "Elk",
    "Deer",
    "Reindeer",
    "Gazelle",
    "Antelope",
    "Bison",
    "Buffalo",
    "Yak",
    "Musk Ox",
    "Wildebeest",
    "Impala",
    "Rhino",
    "Hippo",
    "Warthog",
    "Boar",
    "Pig",
    "Cow",
    "Bull",
    "Ox",
    "Sheep",
    "Ram",
    "Goat",
    "Llama",
    "Alpaca",
    "Camel",
    "Dromedary",
    "Horse",
    "Pony",
    "Donkey",
    "Mule",
    "Zorse",
    "Rabbit",
    "Hare",
    "Guinea Pig",
    "Hamster",
    "Gerbil",
    "Mouse",
    "Rat",
    "Squirrel",
    "Chipmunk",
    "Prairie Dog",
    "Groundhog",
    "Mole",
    "Shrew",
    "Hedgehog",
    "Bat",
    "Fruit Bat",
    "Vampire Bat",
    "Walrus",
    "Seal",
    "Sea Lion",
    "Manatee",
    "Dugong",
    "Narwhal",
    "Beluga Whale",
    "Blue Whale",
    "Humpback Whale",
    "Orca",
    "Sperm Whale",
    "Dolphin",
    "Porpoise",
    "Aardvark",
    "Pangolin",
    "Tasmanian Devil",
    "Quokka",
    "Fennec Fox",
    "Arctic Fox",
    "Sugar Glider",
    "Flying Squirrel",
    "Ferret",
    "Weasel",
    "Stoat",
    "Mink",
    "Chinchilla",
    "Okapi",
    "Bongo",
    "Kudu",
    "Oryx",
    "Dik-dik",
    "Wallaby",
    "Quoll",
    "Bandicoot",
    "Bilby",
    "Numbat",
    "Echidna",

    // Birds
    "Penguin",
    "Ostrich",
    "Emu",
    "Cassowary",
    "Kiwi",
    "Flamingo",
    "Peacock",
    "Swan",
    "Goose",
    "Duck",
    "Mallard",
    "Pelican",
    "Stork",
    "Heron",
    "Crane",
    "Ibis",
    "Spoonbill",
    "Eagle",
    "Hawk",
    "Falcon",
    "Owl",
    "Vulture",
    "Condor",
    "Osprey",
    "Kestrel",
    "Parrot",
    "Macaw",
    "Cockatoo",
    "Parakeet",
    "Budgie",
    "Toucan",
    "Hornbill",
    "Kingfisher",
    "Kookaburra",
    "Woodpecker",
    "Hummingbird",
    "Robin",
    "Sparrow",
    "Blue Jay",
    "Cardinal",
    "Finch",
    "Canary",
    "Goldfinch",
    "Swallow",
    "Swift",
    "Martin",
    "Crow",
    "Raven",
    "Magpie",
    "Jay",
    "Pigeon",
    "Dove",
    "Seagull",
    "Albatross",
    "Puffin",
    "Tern",
    "Cormorant",
    "Booby",
    "Frigatebird",
    "Chicken",
    "Rooster",
    "Hen",
    "Turkey",
    "Quail",
    "Pheasant",
    "Grouse",
    "Partridge",
    "Roadrunner",
    "Mockingbird",
    "Nightingale",
    "Lyrebird",
    "Bird of Paradise",
    "Secretary Bird",
    "Shoebill",

    // Reptiles & Amphibians
    "Crocodile",
    "Alligator",
    "Caiman",
    "Gharial",
    "Turtle",
    "Tortoise",
    "Sea Turtle",
    "Snapping Turtle",
    "Snake",
    "Cobra",
    "Python",
    "Boa Constrictor",
    "Anaconda",
    "Viper",
    "Rattlesnake",
    "Coral Snake",
    "Mamba",
    "Corn Snake",
    "Garter Snake",
    "Lizard",
    "Chameleon",
    "Gecko",
    "Iguana",
    "Komodo Dragon",
    "Monitor Lizard",
    "Gila Monster",
    "Bearded Dragon",
    "Blue-Tongued Skink",
    "Basilisk",
    "Frilled Lizard",
    "Frog",
    "Toad",
    "Tree Frog",
    "Bullfrog",
    "Poison Dart Frog",
    "Salamander",
    "Newt",
    "Axolotl",
    "Caecilian",

    // Fish & Sea Life
    "Shark",
    "Great White Shark",
    "Hammerhead Shark",
    "Tiger Shark",
    "Bull Shark",
    "Whale Shark",
    "Nurse Shark",
    "Ray",
    "Stingray",
    "Manta Ray",
    "Sawfish",
    "Eel",
    "Moray Eel",
    "Electric Eel",
    "Seahorse",
    "Pipefish",
    "Sea Dragon",
    "Clownfish",
    "Surgeonfish",
    "Angelfish",
    "Butterflyfish",
    "Pufferfish",
    "Porcupinefish",
    "Boxfish",
    "Lionfish",
    "Stonefish",
    "Scorpionfish",
    "Tuna",
    "Salmon",
    "Trout",
    "Bass",
    "Catfish",
    "Carp",
    "Goldfish",
    "Koi",
    "Betta",
    "Guppy",
    "Tetra",
    "Anglerfish",
    "Barracuda",
    "Swordfish",
    "Marlin",
    "Sailfish",
    "Sunfish",
    "Flounder",
    "Halibut",
    "Cod",
    "Herring",
    "Anchovy",
    "Sardine",
    "Mackerel",
    "Octopus",
    "Squid",
    "Giant Squid",
    "Cuttlefish",
    "Nautilus",
    "Jellyfish",
    "Box Jellyfish",
    "Man-o-War",
    "Starfish",
    "Sea Urchin",
    "Sea Cucumber",
    "Sand Dollar",
    "Crab",
    "Lobster",
    "Shrimp",
    "Prawn",
    "Krill",
    "Crayfish",
    "Hermit Crab",
    "Fiddler Crab",
    "King Crab",
    "Spider Crab",
    "Barnacle",
    "Clam",
    "Oyster",
    "Mussel",
    "Scallop",
    "Snail",
    "Slug",
    "Nudibranch",
    "Conch",
    "Coral",
    "Anemone",
    "Sponge",

    // Insects & Arachnids
    "Spider",
    "Tarantula",
    "Black Widow",
    "Daddy Longlegs",
    "Scorpion",
    "Tick",
    "Mite",
    "Butterfly",
    "Moth",
    "Caterpillar",
    "Cocoon",
    "Chrysalis",
    "Bee",
    "Honeybee",
    "Bumblebee",
    "Wasp",
    "Hornet",
    "Yellowjacket",
    "Ant",
    "Termite",
    "Beetle",
    "Ladybug",
    "Scarab",
    "Dung Beetle",
    "Stag Beetle",
    "Hercules Beetle",
    "Firefly",
    "Glowworm",
    "Dragonfly",
    "Damselfly",
    "Grasshopper",
    "Cricket",
    "Locust",
    "Katydid",
    "Praying Mantis",
    "Stick Insect",
    "Leaf Insect",
    "Cockroach",
    "Fly",
    "Mosquito",
    "Gnat",
    "Flea",
    "Louse",
    "Bedbug",
    "Cicada",
    "Earwig",
    "Silverfish",
    "Centipede",
    "Millipede",
    "Worm",
    "Earthworm",
    "Leech",

    // Mythical & Extinct
    "Dragon",
    "Unicorn",
    "Pegasus",
    "Griffin",
    "Phoenix",
    "Mermaid",
    "Centaur",
    "Minotaur",
    "Cyclops",
    "Hydra",
    "Kraken",
    "Yeti",
    "Bigfoot",
    "Loch Ness Monster",
    "Chupacabra",
    "Jackalope",
    "Dinosaur",
    "T-Rex",
    "Triceratops",
    "Stegosaurus",
    "Velociraptor",
    "Brachiosaurus",
    "Pterodactyl",
    "Mammoth",
    "Saber-toothed Tiger",
    "Dodo",
    "Tasmanian Tiger",
];

export const rawActions = [
    // Basic Movement
    "Running",
    "Jumping",
    "Walking",
    "Crawling",
    "Sprinting",
    "Jogging",
    "Marching",
    "Tiptoeing",
    "Sneaking",
    "Stumbling",
    "Tripping",
    "Falling",
    "Slipping",
    "Sliding",
    "Rolling",
    "Spinning",
    "Twirling",
    "Leaping",
    "Hopping",
    "Skipping",
    "Galloping",
    "Trotting",
    "Stomping",
    "Waddling",
    "Shuffling",
    "Limping",
    "Climbing",
    "Hiking",
    "Trekking",
    "Wandering",
    "Strolling",
    "Pacing",

    // Water & Air
    "Swimming",
    "Diving",
    "Floating",
    "Treading Water",
    "Surfing",
    "Snorkeling",
    "Scuba Diving",
    "Kayaking",
    "Canoeing",
    "Rowing",
    "Sailing",
    "Paddleboarding",
    "Flying",
    "Gliding",
    "Hovering",
    "Skydiving",
    "Paragliding",
    "Bungee Jumping",
    "Parasailing",

    // Sports & Fitness
    "Boxing",
    "Wrestling",
    "Karate Chopping",
    "Kicking",
    "Punching",
    "Dodging",
    "Blocking",
    "Tackling",
    "Dribbling",
    "Shooting a Ball",
    "Dunking",
    "Serving",
    "Spiking",
    "Volleying",
    "Swinging a Bat",
    "Pitching",
    "Catching",
    "Throwing",
    "Bowling",
    "Golfing",
    "Putting",
    "Skating",
    "Ice Skating",
    "Rollerblading",
    "Skiing",
    "Snowboarding",
    "Sledding",
    "Curling",
    "Fencing",
    "Archery",
    "Weightlifting",
    "Push-ups",
    "Sit-ups",
    "Squats",
    "Lunges",
    "Planking",
    "Yoga",
    "Stretching",
    "Meditating",
    "Jogging",

    // Daily Life & Chores
    "Sleeping",
    "Snoring",
    "Waking Up",
    "Yawning",
    "Stretching",
    "Brushing Teeth",
    "Flossing",
    "Washing Face",
    "Shaving",
    "Combing Hair",
    "Blow Drying Hair",
    "Putting on Makeup",
    "Getting Dressed",
    "Tying Shoes",
    "Buttoning Shirt",
    "Zipping Jacket",
    "Cooking",
    "Chopping",
    "Stirring",
    "Frying",
    "Baking",
    "Grilling",
    "Boiling",
    "Eating",
    "Chewing",
    "Swallowing",
    "Drinking",
    "Sipping",
    "Gulping",
    "Choking",
    "Burping",
    "Hiccuping",
    "Washing Dishes",
    "Drying Dishes",
    "Sweeping",
    "Mopping",
    "Vacuuming",
    "Dusting",
    "Ironing",
    "Folding Laundry",
    "Making the Bed",
    "Taking out Trash",
    "Watering Plants",
    "Mowing the Lawn",
    "Raking Leaves",
    "Shoveling Snow",
    "Gardening",
    "Planting",
    "Weeding",
    "Painting a Wall",
    "Hammering",
    "Sawing",
    "Drilling",
    "Screwing",
    "Fixing",
    "Repairing",

    // Interaction & Communication
    "Talking",
    "Whispering",
    "Shouting",
    "Screaming",
    "Yelling",
    "Singing",
    "Humming",
    "Whistling",
    "Rapping",
    "Beatboxing",
    "Laughing",
    "Giggling",
    "Chuckling",
    "Crying",
    "Sobbing",
    "Weeping",
    "Wailing",
    "Smiling",
    "Frowning",
    "Pouting",
    "Grimacing",
    "Winking",
    "Blinking",
    "Staring",
    "Glaring",
    "Squinting",
    "Nodding",
    "Shaking Head",
    "Shrugging",
    "Pointing",
    "Waving",
    "Clapping",
    "Cheering",
    "Booing",
    "Hugging",
    "Kissing",
    "Holding Hands",
    "High Fiving",
    "Fist Bumping",
    "Handshaking",
    "Saluting",
    "Bowing",
    "Curtsying",
    "Kneeling",
    "Praying",
    "Begging",
    "Arguing",
    "Fighting",
    "Slapping",
    "Pinching",
    "Tickling",
    "Poking",
    "Nudging",
    "Leaning",

    // Hobbies & Leisure
    "Reading",
    "Writing",
    "Drawing",
    "Painting",
    "Sketching",
    "Sculpting",
    "Knitting",
    "Sewing",
    "Crocheting",
    "Quilting",
    "Embroidering",
    "Scrapbooking",
    "Photography",
    "Taking a Selfie",
    "Filming",
    "Acting",
    "Dancing",
    "Ballet",
    "Tap Dancing",
    "Salsa Dancing",
    "Breakdancing",
    "Twerking",
    "Moonwalking",
    "Headbanging",
    "Playing Guitar",
    "Playing Piano",
    "Playing Drums",
    "Playing Violin",
    "Playing Flute",
    "Playing Trumpet",
    "Playing Video Games",
    "Watching TV",
    "Listening to Music",
    "Shopping",
    "Browsing",
    "Trying on Clothes",
    "Paying",
    "Camping",
    "Building a Fire",
    "Roasting Marshmallows",
    "Fishing",
    "Hunting",
    "Birdwatching",
    "Stargazing",

    // Work & Office
    "Typing",
    "Clicking Mouse",
    "Answering Phone",
    "Texting",
    "Emailing",
    "Printing",
    "Stapling",
    "Photocopying",
    "Filing",
    "Signing",
    "Stampeding",
    "Presenting",
    "Teaching",
    "Lecturing",
    "Studying",
    "Taking a Test",
    "Grading",
    "Calculating",
    "Coding",
    "Hacking",
    "Designing",
    "Measuring",
    "Weighing",
    "Mixing Chemicals",
    "Operating Machinery",
    "Driving a Truck",
    "Flying a Plane",
    "Steering a Ship",
    "Directing Traffic",
    "Arresting",
    "Investigating",

    // Abstract & Emotional
    "Thinking",
    "Daydreaming",
    "Wondering",
    "Confused",
    "Scared",
    "Terrified",
    "Shivering",
    "Trembling",
    "Sweating",
    "Blushing",
    "Fainting",
    "Dying",
    "Birthing",
    "Aging",
    "Growing",
    "Shrinking",
    "Melting",
    "Freezing",
    "Burning",
    "Exploding",
    "Sneezing",
    "Coughing",
    "Vomiting",
    "Scratching",
    "Itching",
    "Massaging",
    "Rubbing",
    "Patting",
    "Petting",
    "Feeding",
];

export const rawObjects = [
    // Furniture & Household
    "Table",
    "Chair",
    "Sofa",
    "Couch",
    "Armchair",
    "Recliner",
    "Stool",
    "Bench",
    "Bed",
    "Bunk Bed",
    "Crib",
    "Mattress",
    "Pillow",
    "Blanket",
    "Duvet",
    "Quilt",
    "Sheet",
    "Rug",
    "Carpet",
    "Curtains",
    "Blinds",
    "Lamp",
    "Chandelier",
    "Sconce",
    "Lightbulb",
    "Fan",
    "Ceiling Fan",
    "Air Conditioner",
    "Heater",
    "Radiator",
    "Fireplace",
    "Bookshelf",
    "Cabinet",
    "Cupboard",
    "Drawer",
    "Wardrobe",
    "Closet",
    "Mirror",
    "Painting",
    "Poster",
    "Frame",
    "Vase",
    "Clock",
    "Grandfather Clock",
    "Alarm Clock",
    "Coat Rack",
    "Umbrella Stand",
    "Trash Can",
    "Recycle Bin",
    "Laundry Basket",
    "Ironing Board",

    // Kitchen & Food
    "Fridge",
    "Freezer",
    "Oven",
    "Stove",
    "Microwave",
    "Toaster",
    "Blender",
    "Mixer",
    "Food Processor",
    "Coffee Maker",
    "Kettle",
    "Teapot",
    "Dishwasher",
    "Sink",
    "Faucet",
    "Plate",
    "Bowl",
    "Cup",
    "Mug",
    "Glass",
    "Wine Glass",
    "Fork",
    "Spoon",
    "Knife",
    "Butter Knife",
    "Steak Knife",
    "Chopsticks",
    "Spatula",
    "Whisk",
    "Ladle",
    "Tongs",
    "Peeler",
    "Grater",
    "Can Opener",
    "Corkscrew",
    "Bottle Opener",
    "Cutting Board",
    "Pot",
    "Pan",
    "Skillet",
    "Wok",
    "Baking Sheet",
    "Muffin Tin",
    "Cake Pan",
    "Rolling Pin",
    "Cookie Cutter",
    "Apron",
    "Oven Mitt",
    "Napkin",
    "Tablecloth",
    "Placemat",
    "Salt Shaker",
    "Pepper Mill",
    "Spice Rack",
    "Tupperware",
    "Thermos",
    "Lunchbox",
    "Pizza",
    "Hamburger",
    "Hot Dog",
    "Taco",
    "Burrito",
    "Sushi",
    "Spaghetti",
    "Noodles",
    "Rice",
    "Bread",
    "Toast",
    "Sandwich",
    "Soup",
    "Salad",
    "Steak",
    "Chicken Wing",
    "Egg",
    "Bacon",
    "Sausage",
    "Pancake",
    "Waffle",
    "Cereal",
    "Yogurt",
    "Cheese",
    "Ice Cream",
    "Cake",
    "Pie",
    "Cookie",
    "Donut",
    "Muffin",
    "Croissant",
    "Bagel",
    "Pretzel",
    "Chips",
    "Popcorn",
    "Chocolate",
    "Candy",
    "Lollipop",
    "Gum",
    "Apple",
    "Banana",
    "Orange",
    "Grape",
    "Strawberry",
    "Watermelon",
    "Pineapple",
    "Lemon",
    "Lime",
    "Avocado",
    "Tomato",
    "Potato",
    "Carrot",
    "Broccoli",
    "Corn",
    "Peas",
    "Onion",
    "Garlic",
    "Mushroom",
    "Pepper",
    "Cucumber",
    "Lettuce",
    "Spinach",

    // Technology & Electronics
    "Computer",
    "Laptop",
    "Desktop",
    "Monitor",
    "Keyboard",
    "Mouse",
    "Mousepad",
    "Printer",
    "Scanner",
    "Tablet",
    "iPad",
    "Smartphone",
    "iPhone",
    "Charger",
    "Cable",
    "Battery",
    "Power Bank",
    "Headphones",
    "Earbuds",
    "Speaker",
    "Microphone",
    "Webcam",
    "Camera",
    "DSLR",
    "Tripod",
    "Lens",
    "Flash",
    "Drone",
    "Robot",
    "VR Headset",
    "Smartwatch",
    "Fitbit",
    "Calculator",
    "Television",
    "Remote",
    "Projector",
    "Screen",
    "DVD Player",
    "Blu-ray Player",
    "Game Console",
    "PlayStation",
    "Xbox",
    "Nintendo Switch",
    "Joystick",
    "Controller",
    "Router",
    "Modem",
    "Server",
    "Hard Drive",
    "USB Stick",
    "SD Card",
    "Radio",
    "Walkie Talkie",
    "Satellite Dish",
    "Antenna",
    "Telescope",
    "Microscope",

    // Clothing & Accessories
    "Shirt",
    "T-shirt",
    "Polo Shirt",
    "Blouse",
    "Sweater",
    "Cardigan",
    "Hoodie",
    "Sweatshirt",
    "Jacket",
    "Coat",
    "Raincoat",
    "Parka",
    "Vest",
    "Blazer",
    "Suit",
    "Tuxedo",
    "Dress",
    "Gown",
    "Skirt",
    "Jeans",
    "Pants",
    "Trousers",
    "Shorts",
    "Leggings",
    "Sweatpants",
    "Pajamas",
    "Bathrobe",
    "Underwear",
    "Boxers",
    "Briefs",
    "Bra",
    "Socks",
    "Shoes",
    "Sneakers",
    "Boots",
    "Sandals",
    "Flip Flops",
    "Slippers",
    "Heels",
    "Hat",
    "Cap",
    "Beanie",
    "Beret",
    "Fedora",
    "Cowboy Hat",
    "Helmet",
    "Scarf",
    "Gloves",
    "Mittens",
    "Tie",
    "Bowtie",
    "Belt",
    "Suspenders",
    "Watch",
    "Necklace",
    "Bracelet",
    "Earrings",
    "Ring",
    "Glasses",
    "Sunglasses",
    "Goggles",
    "Mask",
    "Cape",
    "Purse",
    "Handbag",
    "Backpack",
    "Wallet",
    "Suitcase",
    "Luggage",
    "Umbrella",
    "Cane",

    // Tools & Hardware
    "Hammer",
    "Screwdriver",
    "Wrench",
    "Pliers",
    "Saw",
    "Hacksaw",
    "Chainsaw",
    "Drill",
    "Sander",
    "Level",
    "Tape Measure",
    "Ruler",
    "Square",
    "Chisel",
    "File",
    "Clamp",
    "Vise",
    "Anvil",
    "Axe",
    "Hatchet",
    "Shovel",
    "Rake",
    "Hoe",
    "Trowel",
    "Pitchfork",
    "Wheelbarrow",
    "Lawn Mower",
    "Hose",
    "Sprinkler",
    "Ladder",
    "Step Stool",
    "Flashlight",
    "Lantern",
    "Extension Cord",
    "Generator",
    "Pump",
    "Nail",
    "Screw",
    "Bolt",
    "Nut",
    "Washer",
    "Hook",
    "Hinge",
    "Lock",
    "Key",
    "Padlock",
    "Chain",
    "Rope",
    "String",
    "Wire",
    "Duct Tape",
    "Glue",
    "Paintbrush",
    "Roller",
    "Bucket",
    "Mop",
    "Broom",
    "Dustpan",
    "Sponge",
    "Plunger",

    // Office & School
    "Desk",
    "Chair",
    "Cubicle",
    "Whiteboard",
    "Blackboard",
    "Chalk",
    "Marker",
    "Eraser",
    "Pen",
    "Pencil",
    "Highlighter",
    "Crayon",
    "Sharpener",
    "Ruler",
    "Scissors",
    "Glue Stick",
    "Tape",
    "Stapler",
    "Staple",
    "Paper Clip",
    "Binder Clip",
    "Thumbtack",
    "Pin",
    "Rubber Band",
    "Paper",
    "Notebook",
    "Notepad",
    "Journal",
    "Diary",
    "Binder",
    "Folder",
    "Envelope",
    "Letter",
    "Postcard",
    "Stamp",
    "Box",
    "Package",
    "Clipboard",
    "Calculator",
    "Calendar",
    "Globe",
    "Map",
    "Backpack",
    "Lunchbox",
    "Locker",
    "Diploma",

    // Music & Arts
    "Guitar",
    "Electric Guitar",
    "Bass Guitar",
    "Ukulele",
    "Banjo",
    "Mandolin",
    "Violin",
    "Viola",
    "Cello",
    "Double Bass",
    "Harp",
    "Piano",
    "Keyboard",
    "Synthesizer",
    "Organ",
    "Accordion",
    "Drums",
    "Snare Drum",
    "Bass Drum",
    "Cymbal",
    "Tambourine",
    "Maracas",
    "Shaker",
    "Bongos",
    "Congas",
    "Xylophone",
    "Flute",
    "Piccolo",
    "Clarinet",
    "Saxophone",
    "Oboe",
    "Bassoon",
    "Trumpet",
    "Trombone",
    "Tuba",
    "French Horn",
    "Harmonica",
    "Microphone",
    "Amplifier",
    "Speaker",
    "Metronome",
    "Music Stand",
    "Easel",
    "Canvas",
    "Paint",
    "Palette",
    "Brush",
    "Sketchbook",
    "Clay",
    "Pottery Wheel",
    "Kiln",
    "Camera",
    "Film",

    // Vehicles & Transportation
    "Car",
    "Sedan",
    "SUV",
    "Convertible",
    "Limousine",
    "Taxi",
    "Police Car",
    "Ambulance",
    "Fire Truck",
    "Truck",
    "Pickup Truck",
    "Semi Truck",
    "Dump Truck",
    "Garbage Truck",
    "Tow Truck",
    "Bus",
    "School Bus",
    "Van",
    "Minivan",
    "Motorcycle",
    "Scooter",
    "Moped",
    "Bicycle",
    "Tricycle",
    "Unicycle",
    "Skateboard",
    "Rollerblades",
    "Train",
    "Subway",
    "Tram",
    "Trolley",
    "Monorail",
    "Airplane",
    "Jet",
    "Biplane",
    "Glider",
    "Helicopter",
    "Blimp",
    "Hot Air Balloon",
    "Rocket",
    "Spaceship",
    "Satellite",
    "Boat",
    "Rowboat",
    "Canoe",
    "Kayak",
    "Raft",
    "Sailboat",
    "Yacht",
    "Speedboat",
    "Ferry",
    "Cruise Ship",
    "Cargo Ship",
    "Submarine",
    "Tank",
    "Jeep",
    "Tractor",
    "Bulldozer",
    "Excavator",
    "Crane",
    "Forklift",
    "Golf Cart",
    "Segway",
    "Hoverboard",
    "Sled",
    "Sleigh",
    "Carriage",
    "Chariot",

    // Nature & Outdoors
    "Tree",
    "Pine Tree",
    "Palm Tree",
    "Oak Tree",
    "Willow Tree",
    "Bush",
    "Shrub",
    "Flower",
    "Rose",
    "Tulip",
    "Daisy",
    "Sunflower",
    "Lily",
    "Orchid",
    "Cactus",
    "Succulent",
    "Grass",
    "Moss",
    "Fern",
    "Leaf",
    "Branch",
    "Log",
    "Stump",
    "Root",
    "Seed",
    "Nut",
    "Acorn",
    "Pinecone",
    "Rock",
    "Stone",
    "Pebble",
    "Boulder",
    "Sand",
    "Dirt",
    "Mud",
    "Clay",
    "Mountain",
    "Hill",
    "Volcano",
    "Canyon",
    "Cave",
    "Cliff",
    "Valley",
    "River",
    "Stream",
    "Creek",
    "Lake",
    "Pond",
    "Ocean",
    "Sea",
    "Wave",
    "Waterfall",
    "Beach",
    "Island",
    "Desert",
    "Forest",
    "Jungle",
    "Swamp",
    "Glacier",
    "Iceberg",
    "Snow",
    "Snowflake",
    "Hail",
    "Rain",
    "Raindrop",
    "Cloud",
    "Rainbow",
    "Lightning",
    "Thunder",
    "Sun",
    "Moon",
    "Star",
    "Planet",
    "Meteor",
    "Comet",
    "Galaxy",
    "Universe",
    "Black Hole",

    // Weapons & Fantasy (Good for games)
    "Sword",
    "Dagger",
    "Knife",
    "Shield",
    "Spear",
    "Lance",
    "Axe",
    "Mace",
    "Hammer",
    "Bow",
    "Arrow",
    "Crossbow",
    "Slingshot",
    "Catapult",
    "Cannon",
    "Gun",
    "Pistol",
    "Rifle",
    "Shotgun",
    "Machine Gun",
    "Sniper Rifle",
    "Grenade",
    "Bomb",
    "Dynamite",
    "Missile",
    "Rocket",
    "Torpedo",
    "Mine",
    "Trap",
    "Whip",
    "Lasso",
    "Boomerang",
    "Shuriken",
    "Nunchucks",
    "Staff",
    "Wand",
    "Potion",
    "Scroll",
    "Book",
    "Crystal",
    "Orb",
    "Amulet",
    "Ring",
    "Crown",
    "Throne",
    "Treasure Chest",
    "Gold",
    "Jewel",
    "Diamond",
    "Ruby",
    "Emerald",
    "Sapphire",
    "Pearl",
    "Coin",
    "Map",
    "Compass",
    "Key",
    "Torch",
    "Candle",
];

export const rawProfessions = [
    // Medical & Science
    "Doctor",
    "Nurse",
    "Surgeon",
    "Dentist",
    "Veterinarian",
    "Pharmacist",
    "Paramedic",
    "EMT",
    "Midwife",
    "Psychiatrist",
    "Psychologist",
    "Therapist",
    "Chiropractor",
    "Optometrist",
    "Radiologist",
    "Scientist",
    "Biologist",
    "Chemist",
    "Physicist",
    "Astronomer",
    "Geologist",
    "Meteorologist",
    "Botanist",
    "Zoologist",
    "Archeologist",
    "Anthropologist",
    "Historian",
    "Researcher",
    "Lab Technician",

    // Education & Academia
    "Teacher",
    "Professor",
    "Principal",
    "Dean",
    "Librarian",
    "Tutor",
    "Coach",
    "Trainer",
    "Instructor",
    "Student",
    "Scholar",
    "Researcher",
    "Philosopher",

    // Law & Order
    "Police Officer",
    "Detective",
    "Sheriff",
    "Deputy",
    "FBI Agent",
    "CIA Agent",
    "Spy",
    "Secret Agent",
    "Private Investigator",
    "Forensic Scientist",
    "Lawyer",
    "Attorney",
    "Judge",
    "Prosecutor",
    "Defense Attorney",
    "Paralegal",
    "Bailiff",
    "Warden",
    "Guard",
    "Security Guard",
    "Bouncer",
    "Bodyguard",
    "Firefighter",
    "Fire Marshal",
    "Soldier",
    "General",
    "Admiral",
    "Captain",
    "Lieutenant",
    "Sergeant",
    "Sniper",
    "Pilot",

    // Construction & Trades
    "Architect",
    "Engineer",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Builder",
    "Contractor",
    "Carpenter",
    "Mason",
    "Plumber",
    "Electrician",
    "Mechanic",
    "Welder",
    "Painter",
    "Roofer",
    "Landscaper",
    "Gardener",
    "Farmer",
    "Rancher",
    "Logger",
    "Miner",
    "Fisherman",
    "Sailor",
    "Truck Driver",
    "Bus Driver",
    "Taxi Driver",
    "Delivery Driver",
    "Garbage Collector",
    "Janitor",
    "Custodian",
    "Cleaner",
    "Maid",
    "Housekeeper",

    // Food & Service
    "Chef",
    "Cook",
    "Baker",
    "Pastry Chef",
    "Butcher",
    "Waiter",
    "Waitress",
    "Server",
    "Bartender",
    "Barista",
    "Sommelier",
    "Dishwasher",
    "Host",
    "Hostess",
    "Manager",
    "Hotel Manager",
    "Concierge",
    "Bellhop",
    "Receptionist",
    "Secretary",
    "Administrative Assistant",
    "Customer Service Rep",
    "Salesperson",
    "Cashier",
    "Teller",
    "Banker",
    "Accountant",
    "Auditor",
    "Stockbroker",
    "Real Estate Agent",
    "Travel Agent",
    "Flight Attendant",
    "Pilot",
    "Captain",
    "Cruise Director",

    // Arts & Entertainment
    "Artist",
    "Painter",
    "Sculptor",
    "Photographer",
    "Illustrator",
    "Graphic Designer",
    "Fashion Designer",
    "Interior Designer",
    "Writer",
    "Author",
    "Journalist",
    "Reporter",
    "Editor",
    "Poet",
    "Screenwriter",
    "Director",
    "Producer",
    "Actor",
    "Actress",
    "Movie Star",
    "Comedian",
    "Clown",
    "Mime",
    "Magician",
    "Juggler",
    "Acrobat",
    "Circus Performer",
    "Dancer",
    "Ballerina",
    "Choreographer",
    "Musician",
    "Singer",
    "Rapper",
    "DJ",
    "Conductor",
    "Composer",
    "Model",
    "Makeup Artist",
    "Hair Stylist",
    "Barber",
    "Tattoo Artist",

    // Tech & Modern
    "Programmer",
    "Developer",
    "Software Engineer",
    "Web Designer",
    "Hacker",
    "Gamer",
    "Pro Gamer",
    "YouTuber",
    "Streamer",
    "Influencer",
    "Blogger",
    "Podcaster",
    "Social Media Manager",
    "IT Support",
    "Data Analyst",

    // Politics & Leadership
    "Politician",
    "President",
    "Vice President",
    "Governor",
    "Mayor",
    "Senator",
    "Congressman",
    "Diplomat",
    "Ambassador",
    "King",
    "Queen",
    "Prince",
    "Princess",
    "Duke",
    "Duchess",
    "Emperor",
    "Empress",
    "Pharaoh",
    "Sultan",
    "Chief",
    "Dictator",
    "Pope",
    "Bishop",
    "Priest",
    "Nun",
    "Monk",
    "Rabbi",
    "Imam",
    "Pastor",
    "Preacher",

    // Fantasy & Fiction (Great for charades)
    "Wizard",
    "Witch",
    "Sorcerer",
    "Warlock",
    "Mage",
    "Necromancer",
    "Alchemist",
    "Healer",
    "Druid",
    "Ranger",
    "Paladin",
    "Warrior",
    "Barbarian",
    "Rogue",
    "Thief",
    "Assassin",
    "Ninja",
    "Samurai",
    "Knight",
    "Viking",
    "Pirate",
    "Cowboy",
    "Outlaw",
    "Sheriff",
    "Superhero",
    "Supervillain",
    "Sidekick",
    "Ghost",
    "Vampire",
    "Werewolf",
    "Zombie",
    "Mummy",
    "Skeleton",
    "Demon",
    "Angel",
    "God",
    "Goddess",
    "Demigod",
    "Monster",
    "Alien",
    "Robot",
    "Cyborg",
    "Android",
    "Time Traveler",
    "Mad Scientist",
    "Evil Genius",
    "Fairy",
    "Elf",
    "Dwarf",
    "Orc",
    "Goblin",
    "Troll",
    "Giant",
    "Dragon Slayer",

    // Sports
    "Athlete",
    "Olympian",
    "Football Player",
    "Basketball Player",
    "Baseball Player",
    "Soccer Player",
    "Hockey Player",
    "Tennis Player",
    "Golfer",
    "Boxer",
    "Wrestler",
    "Swimmer",
    "Runner",
    "Cyclist",
    "Skater",
    "Skier",
    "Snowboarder",
    "Surfer",
    "Gymnast",
    "Jockey",
    "Race Car Driver",
    "Referee",
    "Umpire",
];

export const rawMovies = [
    // Classics (Pre-2000)
    "The Godfather",
    "The Wizard of Oz",
    "Gone with the Wind",
    "Casablanca",
    "Citizen Kane",
    "Singin' in the Rain",
    "It's a Wonderful Life",
    "Psycho",
    "2001: A Space Odyssey",
    "The Sound of Music",
    "Jaws",
    "Star Wars",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "Alien",
    "Aliens",
    "Blade Runner",
    "E.T.",
    "Raiders of the Lost Ark",
    "Indiana Jones and the Temple of Doom",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "The Breakfast Club",
    "Ferris Bueller's Day Off",
    "The Princess Bride",
    "Dirty Dancing",
    "Top Gun",
    "Die Hard",
    "Ghostbusters",
    "Beetlejuice",
    "Batman",
    "Batman Returns",
    "Edward Scissorhands",
    "Home Alone",
    "Jurassic Park",
    "Schindler's List",
    "Pulp Fiction",
    "Forrest Gump",
    "The Lion King",
    "The Shawshank Redemption",
    "Toy Story",
    "Braveheart",
    "Apollo 13",
    "Clueless",
    "Seven",
    "Independence Day",
    "Mission: Impossible",
    "Titanic",
    "Good Will Hunting",
    "Men in Black",
    "The Fifth Element",
    "The Truman Show",
    "Saving Private Ryan",
    "The Big Lebowski",
    "The Matrix",
    "Fight Club",
    "The Sixth Sense",
    "American Beauty",
    "The Green Mile",
    "Gladiator",
    "Cast Away",

    // Modern Blockbusters & Franchises
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Prisoner of Azkaban",
    "Lord of the Rings: The Fellowship of the Ring",
    "Lord of the Rings: The Two Towers",
    "Lord of the Rings: The Return of the King",
    "Pirates of the Caribbean",
    "Spider-Man",
    "The Dark Knight",
    "The Dark Knight Rises",
    "Inception",
    "Interstellar",
    "Avatar",
    "Avatar: The Way of Water",
    "Iron Man",
    "Captain America",
    "Thor",
    "The Avengers",
    "Guardians of the Galaxy",
    "Black Panther",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Doctor Strange",
    "Spider-Man: No Way Home",
    "Wonder Woman",
    "Aquaman",
    "Joker",
    "The Batman",
    "Man of Steel",
    "Deadpool",
    "Logan",
    "X-Men",
    "Hunger Games",
    "Twilight",
    "Divergent",
    "Maze Runner",
    "Transformers",
    "Fast and Furious",
    "Mission: Impossible - Fallout",
    "Top Gun: Maverick",
    "John Wick",
    "Mad Max: Fury Road",
    "Dune",
    "Oppenheimer",
    "Barbie",
    "La La Land",
    "Whiplash",
    "Parasite",
    "Everything Everywhere All At Once",
    "Knives Out",
    "Glass Onion",
    "Get Out",
    "Us",
    "Nope",
    "A Quiet Place",

    // Animation & Family
    "Shrek",
    "Shrek 2",
    "Finding Nemo",
    "Finding Dory",
    "The Incredibles",
    "Cars",
    "Ratatouille",
    "Wall-E",
    "Up",
    "Toy Story 3",
    "Inside Out",
    "Coco",
    "Soul",
    "Encanto",
    "Moana",
    "Frozen",
    "Frozen II",
    "Zootopia",
    "Tangled",
    "Big Hero 6",
    "Wreck-It Ralph",
    "Despicable Me",
    "Minions",
    "How to Train Your Dragon",
    "Kung Fu Panda",
    "Madagascar",
    "Ice Age",
    "Spirited Away",
    "My Neighbor Totoro",
    "Princess Mononoke",
    "The Lego Movie",
    "Spider-Man: Into the Spider-Verse",
    "Super Mario Bros. Movie",

    // TV Shows (Popular enough to guess)
    "Friends",
    "Seinfeld",
    "The Office",
    "Parks and Recreation",
    "How I Met Your Mother",
    "The Big Bang Theory",
    "Brooklyn Nine-Nine",
    "Modern Family",
    "The Simpsons",
    "Family Guy",
    "SpongeBob SquarePants",
    "Avatar: The Last Airbender",
    "Game of Thrones",
    "Breaking Bad",
    "Better Call Saul",
    "The Sopranos",
    "The Wire",
    "Mad Men",
    "Stranger Things",
    "The Crown",
    "Bridgerton",
    "The Queen's Gambit",
    "Squid Game",
    "Wednesday",
    "The Last of Us",
    "The Mandalorian",
    "WandaVision",
    "Loki",
    "Succession",
    "Ted Lasso",
    "Rick and Morty",
    "Black Mirror",
    "Sherlock",
    "Doctor Who",
    "Downton Abbey",
    "Walking Dead",
    "Lost",
    "Grey's Anatomy",
    "House",
    "Law & Order",
    "NCIS",
    "Criminal Minds",
];

export const rawIdioms = [
    // Visual & Action-Oriented (Easier for Charades)
    "Piece of Cake",
    "Break a Leg",
    "Spill the Beans",
    "Bite the Bullet",
    "Hit the Sack",
    "Under the Weather",
    "Cost an Arm and a Leg",
    "Let the Cat Out of the Bag",
    "Kill Two Birds with One Stone",
    "Barking Up the Wrong Tree",
    "Once in a Blue Moon",
    "Cry Over Spilled Milk",
    "Beat Around the Bush",
    "Burn the Midnight Oil",
    "Caught Red-Handed",
    "Don't Judge a Book by Its Cover",
    "Hit the Nail on the Head",
    "Let Sleeping Dogs Lie",
    "Miss the Boat",
    "Needle in a Haystack",
    "Raining Cats and Dogs",
    "Skeleton in the Closet",
    "Steal Someone's Thunder",
    "Take with a Grain of Salt",
    "The Ball is in Your Court",
    "Through Thick and Thin",
    "Throw in the Towel",
    "Time Flies When You're Having Fun",
    "To Make Matters Worse",
    "Walking on Eggshells",
    "When Pigs Fly",
    "Wild Goose Chase",
    "Your Guess is as Good as Mine",
    "Zip Your Lip",
    "Cold Feet",
    "Butterflies in Stomach",
    "Head in the Clouds",
    "Heart of Gold",
    "Apple of My Eye",
    "Big Cheese",
    "Couch Potato",
    "Early Bird",
    "Night Owl",
    "Social Butterfly",
    "Lone Wolf",
    "Black Sheep",
    "Busy Bee",
    "Eager Beaver",
    "Scaredy Cat",
    "Back to the Drawing Board",
    "Ball and Chain",
    "Basket Case",
    "Beating a Dead Horse",
    "Bed of Roses",
    "Bite Your Tongue",
    "Blind Date",
    "Blood, Sweat, and Tears",
    "Blow Off Steam",
    "Bury the Hatchet",
    "Butterfingers",
    "Cat Got Your Tongue",
    "Chew the Fat",
    "Chip on Your Shoulder",
    "Clean Slate",
    "Cold Shoulder",
    "Cross Your Fingers",
    "Cut Corners",
    "Cut to the Chase",
    "Dead as a Doornail",
    "Devil's Advocate",
    "Don't Count Your Chickens",
    "Down to Earth",
    "Drag Your Feet",
    "Draw the Line",
    "Drop the Ball",
    "Elephant in the Room",
    "Face the Music",
    "Fish Out of Water",
    "Fit as a Fiddle",
    "Fly on the Wall",
    "Foaming at the Mouth",
    "Go the Extra Mile",
    "Green Thumb",
    "Hang in There",
    "Head Over Heels",
    "Hit the Books",
    "Hit the Road",
    "Hold Your Horses",
    "Ice Breaker",
    "In the Doghouse",
    "It Takes Two to Tango",
    "Jump the Gun",
    "Keep Your Chin Up",
    "Kick the Bucket",
    "Knock on Wood",
    "Know the Ropes",
    "Leave No Stone Unturned",
    "Like a Kid in a Candy Store",
    "Long Shot",
    "Loose Cannon",
    "Make Ends Meet",
    "Method to My Madness",
    "Money Talks",
    "Mum's the Word",
    "Neck of the Woods",
    "No Pain, No Gain",
    "Off the Hook",
    "Off the Rocker",
    "Old School",
    "On Cloud Nine",
    "On the Ball",
    "On the Fence",
    "On Thin Ice",
    "Out of the Blue",
    "Over the Moon",
    "Over the Top",
    "Paint the Town Red",
    "Pass the Buck",
    "Pat on the Back",
    "Pig Out",
    "Pipe Dream",
    "Play it by Ear",
    "Pulling Your Leg",
    "Put a Sock in It",
    "Put Your Foot Down",
    "Rags to Riches",
    "Rain Check",
    "Read Between the Lines",
    "Ring a Bell",
    "Rock the Boat",
    "Rolling Out the Red Carpet",
    "Rose Colored Glasses",
    "Rub the Wrong Way",
    "Rule of Thumb",
    "Run out of Steam",
    "Saved by the Bell",
    "See Eye to Eye",
    "Shake a Leg",
    "Shot in the Dark",
    "Sitting Duck",
    "Skeletons in the Closet",
    "Skin of Your Teeth",
    "Sleep on It",
    "Slippery Slope",
    "Smell a Rat",
    "Snug as a Bug in a Rug",
    "Speak of the Devil",
    "Spitting Image",
    "Start from Scratch",
    "Stick to Your Guns",
    "Straight from the Horse's Mouth",
    "Swan Song",
    "Sweet Tooth",
    "Take a Hike",
    "The Last Straw",
    "Think Outside the Box",
    "Third Wheel",
    "Tie the Knot",
    "Tip of the Iceberg",
    "Tongue in Cheek",
    "Top Banana",
    "Touch and Go",
    "Turn a Blind Eye",
    "Two Peas in a Pod",
    "Under the Gun",
    "Up in the Air",
    "Walking on Sunshine",
    "Water Under the Bridge",
    "Wear Your Heart on Your Sleeve",
    "Wet Blanket",
    "Whistleblower",
    "White Elephant",
    "Wolf in Sheep's Clothing",
    "Written in the Stars",
];
