export enum RitualPhase {
    CONGREGATION = "RITUAL_CONGREGATION",
    DIVINATION = "RITUAL_DIVINATION",
    INVOCATION = "RITUAL_INVOCATION",
    MANIFESTATION = "RITUAL_MANIFESTATION",
    REVELATION = "RITUAL_REVELATION",
    SEALED = "RITUAL_SEALED",
}
