export enum Rites {
    CONGREGATION = "CONGREGATION",
    CONSECRATION = "CONSECRATION",
    DIVINATION = "DIVINATION",
    MANIFESTATION = "MANIFESTATION",
    REVELATION = "REVELATION",
    DISSOLUTION = "DISSOLUTION",
}
