export enum Rites {
    CONGREGATION = "CONGREGATION",
    DIVINATION = "DIVINATION",
    INVOCATION = "INVOCATION",
    MANIFESTATION = "MANIFESTATION",
    REVELATION = "REVELATION",
    SEALED = "SEALED",
}
